<template>
  <section class="home">
      <div class="container">
          <div class="row">
              <div class="col">
                  <div class="header">

            <h1>M&M POINT OF SALE SYSTEM</h1>
            <h2>Register Now</h2>
            <button type="button" class="btn btn-outline-primary"><router-link class="router" :to="{ name: 'Register' }"> Register
                                    </router-link></button>
            <h2>Already a member?</h2>
            <button type="button" class="btn btn-outline-primary"><router-link class="router"  :to="{ name: 'Login' }">Login</router-link></button>
            <h2>Already Logged in?</h2>
            <button type="button" class="btn btn-outline-primary"><router-link class="router" :to="{ name: 'Products' }">Click Here</router-link></button>
        </div>  
              </div>
          </div>
      </div>
  </section>
</template>

<script>
export default {
    data(){
        shownav: false
    }
}
</script>

<style scoped>

h1{
    margin-top: 30px;
}

.home{
  background-color: #212529;
   display: flex;
  justify-content: center;
  align-items: center;
  text-align: center;
  min-height: 100vh;
}
.router{
    text-decoration: none;
}
.router:hover{
    color: white;
    
}
.btn-outline-primary {
    
    border-color: #0DB8DE;
    border-radius: 0px;
    font-weight: bold;
    letter-spacing: 1px;
    box-shadow: 0 1px 3px rgba(0, 0, 0, 0.12), 0 1px 2px rgba(0, 0, 0, 0.24);
}

.btn-outline-primary:hover {
background-color: #0DB8DE;
}

.home{

  background:linear-gradient(0deg, rgba(0, 0, 0, 0.7), rgba(0, 0, 0, 0.7)), url('../assets/logo/logo.png');
  background-size:cover;
}

/* ----------------------------------------------
 * Generated by Animista on 2022-3-1 9:44:28
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info. 
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

/**
 * ----------------------------------------
 * animation shadow-drop-2-center
 * ----------------------------------------
 */
@-webkit-keyframes shadow-drop-2-center {
  0% {
    -webkit-transform: translateZ(0);
            transform: translateZ(0);
    -webkit-box-shadow: 0 0 0 0 rgba(0, 0, 0, 0);
            box-shadow: 0 0 0 0 rgba(0, 0, 0, 0);
  }
  100% {
    -webkit-transform: translateZ(50px);
            transform: translateZ(50px);
    -webkit-box-shadow: 0 0 20px 0px rgba(0, 0, 0, 0.35);
            box-shadow: 0 0 20px 0px rgba(0, 0, 0, 0.35);
  }
}
@keyframes shadow-drop-2-center {
  0% {
    -webkit-transform: translateZ(0);
            transform: translateZ(0);
    -webkit-box-shadow: 0 0 0 0 rgba(0, 0, 0, 0);
            box-shadow: 0 0 0 0 rgba(0, 0, 0, 0);
  }
  100% {
    -webkit-transform: translateZ(50px);
            transform: translateZ(50px);
    -webkit-box-shadow: 0 0 20px 0px rgba(0, 0, 0, 0.35);
            box-shadow: 0 0 20px 0px rgba(0, 0, 0, 0.35);
  }
}


</style>